# Generated by Django 5.2.13 on 2026-05-21 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Не был (НБ)'), ('sick', 'Заболел (Б)'), ('excused', 'Отпросился (О)'), ('late', 'Опоздал (Оп)')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
